STORE_APP_ROOT := "StoreApp"

build-styles:
    sass {{STORE_APP_ROOT}}/styles/entry.scss {{STORE_APP_ROOT}}/wwwroot/css/site.css

build-app:
    cd {{STORE_APP_ROOT}} && dotnet build

build-all:
    just build-styles
    just build-app

run: build-app build-styles
    cd {{STORE_APP_ROOT}} && dotnet run

migrate:
    cd {{STORE_APP_ROOT}} && dotnet ef database update

test:
    cd Tests && dotnet test

rebuild-migrations:
    rm -f {{STORE_APP_ROOT}}/store.sqlite
    rm -Rf {{STORE_APP_ROOT}}/Migrations
    cd {{STORE_APP_ROOT}} && dotnet ef migrations add InitialCreate
    just migrate

coverage:
    cd Tests && dotnet test --collect:"XPlat Code Coverage"

coverage-report report:
    reportgenerator -reports:{{report}} -targetdir:Tests/TestResults/report "-reporttypes:Html;TextSummary"