build:
    cd StoreApp && dotnet build

run:
    cd StoreApp && dotnet run

migrate:
    cd StoreApp && dotnet ef database update

test:
    cd Tests && dotnet test

rebuild-migrations:
    rm -f StoreApp/store.sqlite
    rm -Rf StoreApp/Migrations
    cd StoreApp && dotnet ef migrations add InitialCreate
    just migrate

coverage:
    cd Tests && dotnet test --collect:"XPlat Code Coverage"

coverage-report report:
    reportgenerator -reports:{{report}} -targetdir:Tests/TestResults/report "-reporttypes:Html;TextSummary"